//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionTaken) DeepCopyInto(out *ActionTaken) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionTaken.
func (in *ActionTaken) DeepCopy() *ActionTaken {
	if in == nil {
		return nil
	}
	out := new(ActionTaken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringInterval) DeepCopyInto(out *MonitoringInterval) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringInterval.
func (in *MonitoringInterval) DeepCopy() *MonitoringInterval {
	if in == nil {
		return nil
	}
	out := new(MonitoringInterval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatingRange) DeepCopyInto(out *OperatingRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatingRange.
func (in *OperatingRange) DeepCopy() *OperatingRange {
	if in == nil {
		return nil
	}
	out := new(OperatingRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PLCMachine) DeepCopyInto(out *PLCMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PLCMachine.
func (in *PLCMachine) DeepCopy() *PLCMachine {
	if in == nil {
		return nil
	}
	out := new(PLCMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PLCMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PLCMachineList) DeepCopyInto(out *PLCMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PLCMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PLCMachineList.
func (in *PLCMachineList) DeepCopy() *PLCMachineList {
	if in == nil {
		return nil
	}
	out := new(PLCMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PLCMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PLCMachineSpec) DeepCopyInto(out *PLCMachineSpec) {
	*out = *in
	if in.OperatingRanges != nil {
		in, out := &in.OperatingRanges, &out.OperatingRanges
		*out = make([]OperatingRange, len(*in))
		copy(*out, *in)
	}
	if in.ResponseRules != nil {
		in, out := &in.ResponseRules, &out.ResponseRules
		*out = make([]ResponseRule, len(*in))
		copy(*out, *in)
	}
	out.MonitoringInterval = in.MonitoringInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PLCMachineSpec.
func (in *PLCMachineSpec) DeepCopy() *PLCMachineSpec {
	if in == nil {
		return nil
	}
	out := new(PLCMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlantObservation) DeepCopyInto(out *PlantObservation) {
	*out = *in
	if in.Xmeas != nil {
		in, out := &in.Xmeas, &out.Xmeas
		*out = make([]float64, len(*in))
		copy(*out, *in)
	}
	if in.Xmv != nil {
		in, out := &in.Xmv, &out.Xmv
		*out = make([]float64, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlantObservation.
func (in *PlantObservation) DeepCopy() *PlantObservation {
	if in == nil {
		return nil
	}
	out := new(PlantObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PLCMachineStatus) DeepCopyInto(out *PLCMachineStatus) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]VariableStatus, len(*in))
		copy(*out, *in)
	}
	if in.Observation != nil {
		in, out := &in.Observation, &out.Observation
		*out = new(PlantObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.LastAction != nil {
		in, out := &in.LastAction, &out.LastAction
		*out = new(ActionTaken)
		(*in).DeepCopyInto(*out)
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PLCMachineStatus.
func (in *PLCMachineStatus) DeepCopy() *PLCMachineStatus {
	if in == nil {
		return nil
	}
	out := new(PLCMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseRule) DeepCopyInto(out *ResponseRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseRule.
func (in *ResponseRule) DeepCopy() *ResponseRule {
	if in == nil {
		return nil
	}
	out := new(ResponseRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableStatus) DeepCopyInto(out *VariableStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableStatus.
func (in *VariableStatus) DeepCopy() *VariableStatus {
	if in == nil {
		return nil
	}
	out := new(VariableStatus)
	in.DeepCopyInto(out)
	return out
}
